/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ComplianceDocumentWhereUniqueInput } from "../../complianceDocument/base/ComplianceDocumentWhereUniqueInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { ComplianceDocumentListRelationFilter } from "../../complianceDocument/base/ComplianceDocumentListRelationFilter";
import { ContractListRelationFilter } from "../../contract/base/ContractListRelationFilter";
import { DriverWhereUniqueInput } from "../../driver/base/DriverWhereUniqueInput";
import { DriverListRelationFilter } from "../../driver/base/DriverListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";

@InputType()
class TruckWhereInput {
  @ApiProperty({
    required: false,
    type: () => ComplianceDocumentWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ComplianceDocumentWhereUniqueInput)
  @IsOptional()
  @Field(() => ComplianceDocumentWhereUniqueInput, {
    nullable: true,
  })
  complianceDocument?: ComplianceDocumentWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => ComplianceDocumentListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ComplianceDocumentListRelationFilter)
  @IsOptional()
  @Field(() => ComplianceDocumentListRelationFilter, {
    nullable: true,
  })
  complianceDocuments?: ComplianceDocumentListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => ContractListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ContractListRelationFilter)
  @IsOptional()
  @Field(() => ContractListRelationFilter, {
    nullable: true,
  })
  contracts?: ContractListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => DriverWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DriverWhereUniqueInput)
  @IsOptional()
  @Field(() => DriverWhereUniqueInput, {
    nullable: true,
  })
  driver?: DriverWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => DriverListRelationFilter,
  })
  @ValidateNested()
  @Type(() => DriverListRelationFilter)
  @IsOptional()
  @Field(() => DriverListRelationFilter, {
    nullable: true,
  })
  drivers?: DriverListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  registrationNumber?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  truckNumber?: StringNullableFilter;
}

export { TruckWhereInput as TruckWhereInput };
