/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ComplianceDocumentWhereUniqueInput } from "../../complianceDocument/base/ComplianceDocumentWhereUniqueInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { ComplianceDocumentUpdateManyWithoutTrucksInput } from "./ComplianceDocumentUpdateManyWithoutTrucksInput";
import { ContractUpdateManyWithoutTrucksInput } from "./ContractUpdateManyWithoutTrucksInput";
import { DriverWhereUniqueInput } from "../../driver/base/DriverWhereUniqueInput";
import { DriverUpdateManyWithoutTrucksInput } from "./DriverUpdateManyWithoutTrucksInput";

@InputType()
class TruckUpdateInput {
  @ApiProperty({
    required: false,
    type: () => ComplianceDocumentWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ComplianceDocumentWhereUniqueInput)
  @IsOptional()
  @Field(() => ComplianceDocumentWhereUniqueInput, {
    nullable: true,
  })
  complianceDocument?: ComplianceDocumentWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => ComplianceDocumentUpdateManyWithoutTrucksInput,
  })
  @ValidateNested()
  @Type(() => ComplianceDocumentUpdateManyWithoutTrucksInput)
  @IsOptional()
  @Field(() => ComplianceDocumentUpdateManyWithoutTrucksInput, {
    nullable: true,
  })
  complianceDocuments?: ComplianceDocumentUpdateManyWithoutTrucksInput;

  @ApiProperty({
    required: false,
    type: () => ContractUpdateManyWithoutTrucksInput,
  })
  @ValidateNested()
  @Type(() => ContractUpdateManyWithoutTrucksInput)
  @IsOptional()
  @Field(() => ContractUpdateManyWithoutTrucksInput, {
    nullable: true,
  })
  contracts?: ContractUpdateManyWithoutTrucksInput;

  @ApiProperty({
    required: false,
    type: () => DriverWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DriverWhereUniqueInput)
  @IsOptional()
  @Field(() => DriverWhereUniqueInput, {
    nullable: true,
  })
  driver?: DriverWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => DriverUpdateManyWithoutTrucksInput,
  })
  @ValidateNested()
  @Type(() => DriverUpdateManyWithoutTrucksInput)
  @IsOptional()
  @Field(() => DriverUpdateManyWithoutTrucksInput, {
    nullable: true,
  })
  drivers?: DriverUpdateManyWithoutTrucksInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  registrationNumber?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  truckNumber?: string | null;
}

export { TruckUpdateInput as TruckUpdateInput };
