/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ComplianceDocumentWhereUniqueInput } from "../../complianceDocument/base/ComplianceDocumentWhereUniqueInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { ComplianceDocumentCreateNestedManyWithoutTrucksInput } from "./ComplianceDocumentCreateNestedManyWithoutTrucksInput";
import { ContractCreateNestedManyWithoutTrucksInput } from "./ContractCreateNestedManyWithoutTrucksInput";
import { DriverWhereUniqueInput } from "../../driver/base/DriverWhereUniqueInput";
import { DriverCreateNestedManyWithoutTrucksInput } from "./DriverCreateNestedManyWithoutTrucksInput";

@InputType()
class TruckCreateInput {
  @ApiProperty({
    required: false,
    type: () => ComplianceDocumentWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ComplianceDocumentWhereUniqueInput)
  @IsOptional()
  @Field(() => ComplianceDocumentWhereUniqueInput, {
    nullable: true,
  })
  complianceDocument?: ComplianceDocumentWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => ComplianceDocumentCreateNestedManyWithoutTrucksInput,
  })
  @ValidateNested()
  @Type(() => ComplianceDocumentCreateNestedManyWithoutTrucksInput)
  @IsOptional()
  @Field(() => ComplianceDocumentCreateNestedManyWithoutTrucksInput, {
    nullable: true,
  })
  complianceDocuments?: ComplianceDocumentCreateNestedManyWithoutTrucksInput;

  @ApiProperty({
    required: false,
    type: () => ContractCreateNestedManyWithoutTrucksInput,
  })
  @ValidateNested()
  @Type(() => ContractCreateNestedManyWithoutTrucksInput)
  @IsOptional()
  @Field(() => ContractCreateNestedManyWithoutTrucksInput, {
    nullable: true,
  })
  contracts?: ContractCreateNestedManyWithoutTrucksInput;

  @ApiProperty({
    required: false,
    type: () => DriverWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DriverWhereUniqueInput)
  @IsOptional()
  @Field(() => DriverWhereUniqueInput, {
    nullable: true,
  })
  driver?: DriverWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => DriverCreateNestedManyWithoutTrucksInput,
  })
  @ValidateNested()
  @Type(() => DriverCreateNestedManyWithoutTrucksInput)
  @IsOptional()
  @Field(() => DriverCreateNestedManyWithoutTrucksInput, {
    nullable: true,
  })
  drivers?: DriverCreateNestedManyWithoutTrucksInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  registrationNumber?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  truckNumber?: string | null;
}

export { TruckCreateInput as TruckCreateInput };
